<?php

/**
 * @file
 * Code for the Stanford Bean Types Hero feature.
 */

include_once 'stanford_bean_types_hero.features.inc';

/**
 * Implements hook_entity_view().
 */
function stanford_bean_types_hero_entity_view($entity, $type, $view_mode, $langcode) {
//  if ($type == 'bean' && $entity->type == 'stanfords_hero_block') {
    $path = drupal_get_path('module', 'stanford_bean_types_hero');
    $entity->content['#attached']['css'][] = "$path/css/stanford_bean_types_hero.css";
    $entity->content['#attached']['js'][] = "$path/js/stanford_bean_types_hero.js";
//  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function stanford_bean_types_hero_form_bean_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#bundle'] == 'stanfords_hero_block') {
    $form['title']['#type'] = 'hidden';
  }
}
