<?php

/**
 * @file
 * Code for the Stanford Icon Grid Block feature.
 */

include_once 'stanford_icon_grid.features.inc';

/**
 * Implements hook_preprocess_field().
 */
function stanford_icon_grid_preprocess_field(&$vars) {
  if ($vars['element']['#field_name'] == 'field_s_icon_ext_columns') {
    $offset = 0;

    // If not a multiple of 3, set the offset to center the field item.
    if (count($vars['items']) % 3) {
      $offset = -2 * (count($vars['items']) % 3 - 3);
    }

    foreach ($vars['items'] as $delta => &$item) {
      $item['#attributes']['class'][] = 'span4';

      // Sets the offset to the first item of the last group of 3. Ex:
      // 1 or 2 items - the very first will get the offset. 4 or 5 - the 4th
      // item will get the offset and so on.
      if ($offset && !($delta % 3) && count($vars['items']) - $delta < 3) {
        $item['#attributes']['class'][] = "offset$offset";
      }
    }
  }
}

/**
 * Implements hook_field_attach_form().
 */
function stanford_icon_grid_field_attach_form($entity_type, $entity, &$form, &$form_state, $langcode) {
  if (isset($form['field_s_icon_ext_columns_bg_colo'])) {
    drupal_add_js(drupal_get_path('module', 'stanford_icon_grid') . '/js/stanford_icon_grid.js');
  }
}

/**
 * Implements hook_preprocess_entity().
 */
function stanford_icon_grid_preprocess_entity(&$vars) {
  $entity = $vars['elements']['#entity'];
  if ($vars['entity_type'] != 'field_collection_item' || $entity->field_name != 'field_s_icon_ext_columns') {
    return;
  }
  drupal_add_css(drupal_get_path('module', 'stanford_icon_grid') . '/css/stanford_icon_grid.css');

  $colors = $entity->field_s_icon_ext_columns_bg_colo[LANGUAGE_NONE][0]['value'];
  if (strpos($colors, ',') !== FALSE) {
    list($background, $font) = explode(',', $colors);
    $vars['classes_array'][] = 'icon-color-' . trim($font, ', #');
  }
  else {
    $background = $colors;
  }

  $vars['classes_array'][] = 'icon-background-' . trim($background, ', #');
}

/**
 * Implements hook_entity_view_mode_alter().
 */
function stanford_icon_grid_entity_view_mode_alter(&$view_mode, $context) {
  if ($context['entity_type'] == 'field_collection_item' && $context['entity']->field_name == 'field_s_icon_ext_columns') {
    switch ($context['entity']->field_s_icon_ext_columns_style[LANGUAGE_NONE][0]['value']) {
      case 'image':
        $view_mode = 'stanford_block';
        break;

      case 'text':
        $view_mode = 'stanford_list';
        break;
    }
  }
}

/**
 * Implements hook_theme_registry_alter().
 *
 * @see https://www.drupal.org/docs/7/creating-custom-modules/howtos/using-template-tplphp-files-in-your-own-module
 */
function stanford_icon_grid_theme_registry_alter(&$theme_registry) {
  $module_path = drupal_get_path('module', 'stanford_icon_grid');
  $template_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
  foreach ($template_objects as $key => $template_object) {
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}
